import type { Metadata } from "next";
import Link from "next/link";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import ProductSearch from "../../components/ProductSearch";
import { productCategories } from "../../lib/products";

export const metadata: Metadata = { title: "Ürünler | M&Y Kozmetik", description: "M&Y Kozmetik profesyonel kuaför ve güzellik salonları için kozmetik ve sarf malzemeleri." };

export default function UrunlerPage() {
  return <main className="min-h-screen bg-[#090909] text-white overflow-hidden"><Navbar />
    <section className="relative pt-40 pb-24 overflow-hidden"><div className="absolute inset-0 pointer-events-none"><div className="absolute top-10 right-0 w-[650px] h-[550px] rounded-full bg-[#D4AF37]/8 blur-[170px]" /><div className="absolute bottom-0 left-0 w-[450px] h-[450px] rounded-full bg-[#D4AF37]/5 blur-[150px]" /></div><div className="relative max-w-7xl mx-auto px-6 lg:px-8"><div className="page-top" style={{ animationDelay: "0.15s" }}><span className="text-[#D4AF37] text-xs tracking-[5px] uppercase">M&Y Professional Cosmetics</span></div><h1 className="mt-5 text-5xl lg:text-7xl font-black leading-tight"><span className="page-left inline-block" style={{ animationDelay: "0.3s" }}>Profesyonel</span><br /><span className="page-left inline-block text-[#D4AF37]" style={{ animationDelay: "0.45s" }}>Ürünler</span></h1><p className="page-left mt-7 max-w-2xl text-zinc-400 text-lg leading-8" style={{ animationDelay: "0.6s" }}>Kuaför, güzellik merkezi ve profesyonel salonların günlük ihtiyaçlarına yönelik ürün gruplarını keşfedin.</p></div></section>
    <section className="pb-32"><div className="max-w-7xl mx-auto px-6 lg:px-8"><div className="page-bottom mb-12" style={{ animationDelay: "0.7s" }}><ProductSearch /></div><div className="page-bottom mb-10" style={{ animationDelay: "0.82s" }}><span className="text-[#D4AF37] text-xs tracking-[4px] uppercase">Ürün Kategorileri</span><h2 className="mt-4 text-3xl font-bold">Profesyonel Ürünler</h2></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{productCategories.map((category, index) => <Link key={category.slug} href={"/urunler/" + category.slug} className={"group rounded-[30px] border border-white/10 bg-white/[0.025] p-8 hover:border-[#D4AF37]/40 hover:bg-white/[0.04] transition-all duration-500 " + (index % 2 === 0 ? "page-left" : "page-right")} style={{ animationDelay: (0.85 + index * 0.15) + "s" }}><div className="flex items-start justify-between"><span className="text-[#D4AF37] text-xs tracking-[4px]">0{index + 1}</span><span className="text-zinc-600 group-hover:text-[#D4AF37] transition-colors text-xl">↗</span></div><h2 className="mt-12 text-2xl font-bold">{category.name}</h2><p className="mt-4 text-zinc-500 leading-7">{category.description}</p><div className="mt-8 text-sm text-[#D4AF37]">Ürünleri Görüntüle ↗</div></Link>)}<div className="page-bottom rounded-[30px] border border-[#D4AF37]/20 bg-[#D4AF37]/[0.04] p-8 hover:bg-[#D4AF37]/[0.07] transition-all duration-500" style={{ animationDelay: "1.5s" }}><span className="text-[#D4AF37] text-xs tracking-[4px] uppercase">M&Y</span><h2 className="mt-12 text-2xl font-bold">Yeni Ürünler</h2><p className="mt-4 text-zinc-500 leading-7">Ürün yelpazemiz genişledikçe yeni kategoriler burada yer alacak.</p><Link href="/iletisim" className="inline-block mt-8 text-sm text-[#D4AF37] hover:text-white transition-colors">Bilgi Al →</Link></div></div></div></section><Footer />
  </main>;
}

