import Image from "next/image";
import Link from "next/link";
import Navbar from "./Navbar";
import Footer from "./Footer";
import type { Product, ProductCategory } from "../lib/products";

export default function ProductDetailPage({ category, product }: { category: ProductCategory; product: Product }) {
  const whatsappMessage = encodeURIComponent(`Merhaba, ${product.name} ürünü hakkında bilgi almak istiyorum.`);
  return <main className="min-h-screen bg-[#090909] text-white overflow-hidden"><Navbar />
    <section className="relative pt-40 pb-24 overflow-hidden"><div className="absolute inset-0 pointer-events-none"><div className="absolute top-10 right-0 w-[650px] h-[550px] rounded-full bg-[#D4AF37]/8 blur-[170px]" /><div className="absolute bottom-0 left-0 w-[450px] h-[450px] rounded-full bg-[#D4AF37]/5 blur-[150px]" /></div><div className="relative max-w-7xl mx-auto px-6 lg:px-8"><div className="page-top" style={{ animationDelay: "0.15s" }}><span className="text-[#D4AF37] text-xs tracking-[5px] uppercase">{product.brand}</span></div><Link href={"/urunler/" + category.slug} className="page-left inline-flex mt-5 text-zinc-500 hover:text-[#D4AF37] transition-colors text-sm" style={{ animationDelay: "0.25s" }}>← {category.name}</Link><h1 className="page-left mt-6 max-w-4xl text-5xl lg:text-7xl font-black leading-tight" style={{ animationDelay: "0.4s" }}><span className="text-[#D4AF37]">{product.name}</span></h1><p className="page-left mt-7 max-w-2xl text-zinc-400 text-lg leading-8" style={{ animationDelay: "0.55s" }}>{product.shortDescription}</p></div></section>
    <section className="pb-32"><div className="max-w-7xl mx-auto px-6 lg:px-8"><div className="grid lg:grid-cols-2 gap-6"><div className="page-left min-h-[420px] rounded-[35px] border border-white/10 bg-white/[0.025] flex items-center justify-center p-8" style={{ animationDelay: "0.7s" }}>{product.image ? <Image src={product.image} alt={product.name} width={640} height={640} className="h-full max-h-[520px] w-full object-contain" priority /> : <span className="text-zinc-700 text-sm">Ürün Fotoğrafı</span>}</div><div className="page-right rounded-[35px] border border-white/10 bg-white/[0.025] p-8 lg:p-12" style={{ animationDelay: "0.85s" }}><span className="text-[#D4AF37] text-xs tracking-[4px] uppercase">Ürün Detayı</span><h2 className="mt-5 text-3xl font-bold">{product.name}</h2><p className="mt-6 text-zinc-400 leading-8">{product.shortDescription} Ürün ve toplu alım seçenekleri hakkında bizimle iletişime geçebilirsiniz.</p><div className="mt-10 border-t border-white/10 pt-8"><span className="text-zinc-500 text-sm">Kategori</span><p className="mt-2 font-semibold">{category.name}</p></div><a href={`https://wa.me/905449964058?text=${whatsappMessage}`} target="_blank" rel="noopener noreferrer" className="inline-flex mt-10 bg-[#D4AF37] text-black font-semibold px-7 py-3.5 rounded-full hover:scale-105 transition-transform duration-300">Bilgi Al</a></div></div></div></section><Footer />
  </main>;
}

