import Image from "next/image";
import Link from "next/link";
import Navbar from "./Navbar";
import Footer from "./Footer";
import type { ProductCategory } from "../lib/products";

export default function ProductCatalogPage({ category }: { category: ProductCategory }) {
  return <main className="min-h-screen bg-[#090909] text-white overflow-hidden"><Navbar />
    <section className="relative pt-40 pb-24 overflow-hidden"><div className="absolute inset-0 pointer-events-none"><div className="absolute top-10 right-0 w-[650px] h-[550px] rounded-full bg-[#D4AF37]/8 blur-[170px]" /><div className="absolute bottom-0 left-0 w-[450px] h-[450px] rounded-full bg-[#D4AF37]/5 blur-[150px]" /></div><div className="relative max-w-7xl mx-auto px-6 lg:px-8"><div className="page-top" style={{ animationDelay: "0.15s" }}><span className="text-[#D4AF37] text-xs tracking-[5px] uppercase">M&Y Professional Cosmetics</span></div><Link href="/urunler" className="page-left inline-flex mt-5 text-zinc-500 hover:text-[#D4AF37] transition-colors text-sm" style={{ animationDelay: "0.25s" }}>← Ürünler</Link><h1 className="mt-6 text-5xl lg:text-7xl font-black leading-tight"><span className="page-left inline-block" style={{ animationDelay: "0.4s" }}>Profesyonel</span><br /><span className="page-left inline-block text-[#D4AF37]" style={{ animationDelay: "0.55s" }}>{category.name}</span></h1><p className="page-left mt-7 max-w-2xl text-zinc-400 text-lg leading-8" style={{ animationDelay: "0.7s" }}>{category.description}</p></div></section>
    <section className="pb-32"><div className="max-w-7xl mx-auto px-6 lg:px-8"><div className="page-left mb-10" style={{ animationDelay: "0.85s" }}><span className="text-[#D4AF37] text-xs tracking-[4px] uppercase">Ürün Kataloğu</span><h2 className="mt-4 text-3xl font-bold">{category.name}</h2></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{category.products.map((product, index) => <Link key={product.slug} href={"/urunler/" + category.slug + "/" + product.slug} className={"group rounded-[30px] border border-white/10 bg-white/[0.025] overflow-hidden hover:border-[#D4AF37]/40 hover:bg-white/[0.04] transition-all duration-500 " + (index % 3 === 0 ? "page-left" : index % 3 === 1 ? "page-bottom" : "page-right")} style={{ animationDelay: (0.95 + index * 0.12) + "s" }}><div className="h-64 bg-white/[0.02] flex items-center justify-center group-hover:bg-[#D4AF37]/[0.04] transition-colors p-6">{product.image ? <Image src={product.image} alt={product.name} width={420} height={420} className="h-full w-full object-contain transition-transform duration-500 group-hover:scale-[1.03]" /> : <span className="text-zinc-700 text-sm">Ürün Fotoğrafı</span>}</div><div className="p-7"><span className="text-[#D4AF37] text-xs tracking-[3px] uppercase">{product.brand}</span><h3 className="mt-4 text-xl font-semibold">{product.name}</h3><p className="mt-3 text-zinc-500 text-sm leading-6">{product.shortDescription}</p><span className="inline-block mt-6 text-sm text-[#D4AF37]">Detayı Görüntüle ↗</span></div></Link>)}</div></div></section><Footer />
  </main>;
}

